### ISSUE TITLE
 bug: Uncaught TypeError: Cannot read properties of undefined (reading 'syncadaptor') #346 

### ISSUE THREAD

**Issue by linonetwo** [twcloud/tiddlyweb-sse#4]
tiddly-gittly/TidGi-Desktop#346

Caused in single html wiki https://github.com/tiddly-gittly/Tiddlywiki-NodeJS-Github-Template

**Comment by linonetwo** [comment]
@Arlen22 do you still active? I think I may have to fork this repo to https://github.com/tiddly-gittly/

**Comment by Arlen22** [comment]
Yes, I am. Hadn't seen this before. I'll look into it.

**Comment by linonetwo** [comment]
Maybe you haven't watch the issue of this repo.

Thanks, today another tiddloid user report this.

**Comment by linonetwo** [comment]
@Arlen22 This is causing more troubles! Bump for a fix

**Comment by Arlen22** [comment]
@linonetwo , the startup tiddler `$:/plugins/twcloud/tiddlyweb-sse/sse-client.js` requires the tiddlyweb syncadaptor to be active. 

I'll fix one of the things that I see here, which should at least make the plugin properly inert when the tiddlyweb syncadaptor is not available. Hopefully that fixes the issue for you.

**Comment by linonetwo** [comment]
Thanks, not prompint error is enough for users to accept this.

How will you release it? CPL point to https://github.com/twcloud/tiddlyweb-sse/releases/latest/download/plugin.info , if you update that json (by a new release! And don't forget to upgrade version info), users can click the upgrade button to fix it for them. https://tw-cpl.netlify.app/#twcloud%2Ftiddlyweb-sse

**Comment by linonetwo** [comment]
@Arlen22 better rename plugin.info to plugin.json

**Comment by linonetwo** [comment]
@Arlen22 Users are still suffering from this bug!

![图片](https://github.com/twcloud/tiddlyweb-sse/assets/3746270/72b3c87d-635e-4835-9307-3594363cf3dd)

**Comment by Arlen22** [comment]
@linonetwo is that because they haven't updated? Or is that based on master? Just checking. I'm working on a release right now.

**Comment by Arlen22** [comment]
Ok, I added the release. Could you check it and let me know if I did everything right? Thanks.

**Comment by Arlen22** [comment]
@linonetwo , I also added https://github.com/twcloud/tiddlyweb-sse/pull/2 as a separate release. Please check both of them and make sure they are working properly. Thanks.

**Comment by linonetwo** [comment]
Thanks， I think this works. Let me update the CPL later.

Only after that, user can receive updates.

**Comment by linonetwo** [comment]
CPL is serving latest version, thanks.
